### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dongdaoguang** [pingcap/titan#16]
I use rocksdb rocksdb-6.0.2, when build titan, it gives me an error:
/proj/titan/src/util.cc:16:15: error: ‘const class rocksdb::CompressionContext’ has no member named ‘type’
   *type = ctx.type();

So, I want to know which rocksdb version does titan use?

**Comment by tabokie** [comment]
Currently Titan only works with pingcap's internal fork of rocksdb (https://github.com/pingcap/rocksdb), we will fix these compatibility issues later.

**Comment by dongdaoguang** [comment]
I see, thank you for your answer.
